# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='username',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
