# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadfile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='filename',
            field=models.CharField(default='admin_file', max_length=1000),
        ),
    ]
