# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_uploadfile_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
