# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Finished', max_length=10),
        ),
    ]
