# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='outfile_location',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='outfile_name',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='raw_files/%Y/%m/%d'),
        ),
    ]
