# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20161001_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='outfile_location',
            field=models.CharField(default='a', max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='outfile_name',
            field=models.CharField(default='b', max_length=1000),
        ),
    ]
