# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161001_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='outfile_location',
        ),
        migrations.RemoveField(
            model_name='task',
            name='outfile_name',
        ),
    ]
