# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161001_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(default='a', max_length=1000),
        ),
    ]
