# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_task_submit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='speed',
            field=models.CharField(default='ssm', max_length=3),
        ),
        migrations.AddField(
            model_name='task',
            name='ssmiter',
            field=models.IntegerField(default='20'),
        ),
        migrations.AddField(
            model_name='task',
            name='threshold',
            field=models.IntegerField(default=10),
        ),
    ]
