# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20161013_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='thumbnail_xy',
            field=models.FileField(default=None, upload_to='raw_files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='thumbnail_xz',
            field=models.FileField(default=None, upload_to='raw_files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='thumbnail_yz',
            field=models.FileField(default=None, upload_to='raw_files/%Y/%m/%d'),
        ),
    ]
