# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='storage_used',
            field=models.FloatField(default=0),
        ),
    ]
