# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPanel', '0002_remove_historytask_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytask',
            name='file_field',
            field=models.FileField(default='Please choose files', upload_to=''),
        ),
    ]
