# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPanel', '0003_historytask_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytask',
            name='file_field',
            field=models.FileField(default='Please choose files', upload_to='./upload/'),
        ),
        migrations.AlterField(
            model_name='historytask',
            name='user',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
