# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPanel', '0004_auto_20160913_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historytask',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='historytask',
            name='filename',
        ),
        migrations.AlterField(
            model_name='historytask',
            name='file_field',
            field=models.FileField(default='Please choose files', upload_to=''),
        ),
    ]
