# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPanel', '0005_auto_20160913_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='historytask',
            name='task_desc',
            field=models.CharField(default='Please input descriptions', max_length=1000),
        ),
    ]
