# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPanel', '0006_historytask_task_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytask',
            name='file_field',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='historytask',
            name='user',
            field=models.CharField(default='Admin', max_length=1000),
        ),
    ]
